### ISSUE TITLE
Accessing HTML fixture

### ISSUE THREAD

**Issue by patocallaghan** [anacronw/js-fixtures#10]
Hey, 

maybe I'm not understanding how to use this library correctly but I can't seem to get it work with my JS libraries. I'm finding that because my fixture HTML is added within the iframe it can't access it.

For example,

I have an AMD module which looks something like this:

```
define(['jquery', 'rotatorPlugin', function($){
   return {
      init: function(){
        $('#my-rotator-fixture').rotatorPlugin();
      }
   };
});
```

I then have a spec like this:

```
define(['jquery', 'app/ui/rotator'], function($, Rotator){
    describe('the Rotator Module', function() {
        it('should correctly init the rotator on the page', function() {

            //Setup
                        fixtures.load('rotator.html');
            $rotator = $('.js-rotator');

            //Work
            Rotator.init();

            //Assertion
            expect($rotator).to.have.data('rotatorPlugin');
        });
    });
})
```

I'm finding though that in my spec and Rotator module when running `$('.js-rotator').length` it returns`0` unless I specifically target the iframe. Is this what should be happening? This is a very simplified example, I know, but by not having access to the fixtures outside of the iframe does this mean I have to pass in all the DOM elements I want to test in my AMD modules?

Thanks,
Pat

**Comment by anacronw** [comment]
yes, its as you said, because the fixture is loaded through an iframe, $('.js-rotator') is not available in the current frame context.  Its a little cumbersome, but while I was writing some dom traversal library, I found the test runner itself was affecting my own tests so I took the time to split it up.

If you're writing a jquery plugin, I suggest that you load jquery itself into your fixtures.  You can then access it via:

``` javascript
var $$ = fixtures.window().$
```

This jquery instance is separate from the one that you may have loaded through the test runner.  In there, $$('.js-rotator') should be there if the fixture was loaded.

Let me know if this works/doesn't work for you. :)

**Comment by patocallaghan** [comment]
Hey, thanks for the response.

If I understand you correctly that will only fix the context issue within the specs but not within the actual modules I'm testing. I don't think that will work for me as that will require me to rewrite my modules so that they don't do DOM retrieval in the current context. I'd have to pass in the context to each of them at init time `window` when running in production and `fixtures.window()` when within the tests.

For example, within my Rotator module example above I'd have to do something like this? `Rotator.init(window)` and in the rest of the module make sure I don't do any DOM Retrieval without using the current context as the root.

Is that correct?

**Comment by anacronw** [comment]
You should be able to load both your rotator module and jquery (along with whatever other dependencies you want to test) within the iframe.  Just think of it as a blank slate that you can always clear.  Your jquery module should work with whatever context its loaded with, so for convenience sake, I would write a fixture that looks like this:

```
<script src="path/to/jquery"></script>
<script src="path/to/rotator"></script>
```

Then your spec would look something like this:

``` javascript
$rotator;
beforeEach(function(){
    fixtures.load('/path/to/fixture');
    $rotator = fixtures.window().$('.js-rotator');
})
afterEach(function(){
    fixtures.cleanUp();
})
 it('should correctly init the rotator on the page', function() {
    Rotator.init();
    expect($rotator).to.have.data('rotatorPlugin');
});
```

With this iframe, you can also test whether your plugin is loading correctly with and without an AMD loader despite your test harness having one, but that would have to be loaded through the fixtures as well.

Edit: In other words, don't load the plugin through the AMD loader of your test harness as it will load it through the current window's context.  You want to load it from within fixtures (with or without an AMD loader).

**Comment by patocallaghan** [comment]
Ah okay, I get you know. I wasn't understanding before that I load all my dependencies through the fixture. That makes more sense. Thanks for your help.

**Comment by anacronw** [comment]
Lmk if you have other questions - I should perhaps update the README with examples
