### ISSUE TITLE
load has a synchronous API, but is actually somewhat async

### ISSUE THREAD

**Issue by dmose** [anacronw/js-fixtures#15]
Which is to say, I'm trying to use js-fixtures for integration testing.  This means I'm using the real main page of my app, which has a whole bunch of different things.

The usage pattern described in the README blows with $$ being undefined, because, I think, the jQuery script load inside the fixture hasn't finished by the time the call to load() returns.  The evidence for this is that if I set a breakpoint in a JS debugger just before assigning to $$, and then step a couple of lines, (with the human delay giving the jQuery load time to complete), then the next statement executes without error.

**Comment by anacronw** [comment]
Thanks,

I think I see what you mean, I will give it a try on my end later tonight.  It may be an obvious use case that I hadn't thought of before.

For now, so that you're not blocked, could you actually download jquery and place the code inline as a fixture?  That should cause it to load synchronously.

**Comment by dmose** [comment]
Thanks much; I appreciate the prompt response, and the thoughtfulness towards helping me stay unblocked.

I just tried your suggestion, and it does indeed workaround the problem (and would seem to support the race-condition theory).

I'm not quite blocked yet, as I'm just at the stage of experimenting with different packages that might be suitable for this sort of integration testing.  But I'm hoping to find something I can commit to this week.  One of the other packages I'm planning to look at is a different port of js-fixtures, https://github.com/kevindente/jsFixtures. I'm a bit concerned that that one doesn't have any forks and hasn't seen any changes lately in the last few years. So it's all a bit up-in-the-air.  :-) 

All that said, he's chosen an API which would seem to solve this problem (though I haven't yet tested whether it actually solves it for the code I'm working with) in a fairly elegant way, so you might consider trying something similar.  A doc snippet:

load(fixtureUrl[, fixtureUrl, ..., cb])

Loads fixture(s) from one or more files and automatically appends them to the DOM (to the fixtures container). If the last parameter is a callback function, then the load happens asynchronously, and the callback is invoked when the fixture data is available. If no callback is provided, then the fixture data is loaded synchronously

**Comment by anacronw** [comment]
I couldn't find time tonight, but that's a great idea

I actually don't think it'll fix your use case however.  To some extent, it can only tell whether the fixture was loaded and not whether jquery is available, I'd imagine it would run into the same issues

Perhaps another workaround is to load jquery first, and then a 2nd inline thing.  The browser should naturally wait till the first is loaded before proceeding

**Comment by dmose** [comment]
Interestingly, I'm seeing this race condition with multiple libraries.

I think the interface itself is compatibility with a fix that would work with integration testing, but you're quite right that the implementation would need to have a way to tell when the load was truly done.  Looking at the code, the innertHTML is used, which looks like it might mean interesting things for HTML5 documents, namely that browsers might simply refuse to run scripts appended via innerHTML in docs with HTML5 doctypes (assuming that https://developer.mozilla.org/en-US/docs/Web/API/Element.innerHTML#Security_considerations actually describes what browsers implement or will implement).

Have you thought about loading the content by setting iframe.src and/or (for HTML5) iframe.srcdoc?  This would seem to get around the above restrictions, and would seem to suggest that the asynchronous load case could be supported by calling the load callback from a load handler attached to the iframe's window, which would only fire after all the relevant javascript was loaded.

**Comment by dmose** [comment]
Looks like the implementation for at least the integration use case (ie loading the actual HTML app in the iframe, rather than just a tiny fixture -- the one that's hitting me in the moment) is actually easier: my load is going through createContainer, which uses document.write, which is why the script tags are used at all, and a quick hack attempt adding an iframe.contentWindow.onload in that function at least showed that it got called.

**Comment by dmose** [comment]
Also, I tried your workaround:

> Perhaps another workaround is to load jquery first, and then a 2nd inline thing. The browser should naturally wait 
> till the first is loaded before proceeding"

This didn't actually work, and my suspicion is that because, as implemented now, load is effectively async (even though the interface doesn't yet allow for a callback), because it returns without waiting on the load event in the content window.

Thanks for the suggestion, though.   :-)

I'll continue to poke around.

**Comment by dmose** [comment]
I just did a hack-n-slash prototype of giving load a callback, and it does work and solve the problem described here:

https://gist.github.com/anonymous/7363034

**Comment by anacronw** [comment]
awesome! do you mind submitting a PR?

**Comment by anacronw** [comment]
I have to do some more tests.  I can reproduce the problem you're seeing in a test, however I realized a whole slew of new problems.

For example, https://github.com/badunk/js-fixtures/issues/8 is the only reason why it works in the first place - subsequent script insertions go into the body with .innerHTML, which are not allowed to be executed according to the html5 spec.

I certainly like the callback idea, however.  I just feel like this library needs a bit of refactoring of its approach.

**Comment by dmose** [comment]
Re innerHTML, browsing StackOverflow suggests that the HTML5 spec is mostly just codifying existing practice -- browsers already don't support that.  One approach I could imagine to handling subsequent insertions might be simply slice out the script tags, remember where they were, insert everything else using innerHtml on a DOM node that's not attached to the DOM, add in the script nodes to the appropriate spot using appendChild, and then appendChild the entire fragment to the DOM.  Or something.  :-)

**Comment by dmose** [comment]
Another perspective is that for the integration testing using case, it's not obvious to me that subsequent insertions would be desirable or necessary.  So I could imagine simply leaving "JS-in-non-initial-insertions" as something to be implemented as-needed in the future.

**Comment by anacronw** [comment]
Oh, the reason why I would do subsequent insertions is simply to add multiple dependent libraries as part of a setup.

I think what you're saying makes sense, I'll work on a fix for the short term as I think I'm close.  Perhaps I would have to expose adding javascript as a different method over html fixtures in a future enhancement.

**Comment by dmose** [comment]
Awesome; thanks!

**Comment by anacronw** [comment]
it was a little more difficult than I thought b/c I forgot I'm supporting the signature:

```
fixtures.load('url', 'url', 'url', ...)
```

didn't want to break that compatibility.  Anyways, the included test in this commit should check for your specific jquery case, please check it out
