### ISSUE TITLE
load's callback argument doesn't work

### ISSUE THREAD

**Issue by davidascher** [anacronw/js-fixtures#17]
at least as far as i can tell, load(uri, cb) never calls cb() because load passes it to addToContainer, which ignores it.

**Comment by anacronw** [comment]
https://github.com/badunk/js-fixtures/blob/master/fixtures.js#L87

It delegates it to createContainer: https://github.com/badunk/js-fixtures/blob/master/fixtures.js#L63

**Comment by anacronw** [comment]
also, please see if this test works for you:

https://github.com/badunk/js-fixtures/blob/master/test/fixtures-spec.js#L127-L147

**Comment by davidascher** [comment]
ignore me, apologies.

**Comment by anacronw** [comment]
np :smile:
