### ISSUE TITLE
cb argument duplicated

### ISSUE THREAD

**Issue by MichaelXavier** [anacronw/js-fixtures#25]
Hi,

Thanks for this library. When using the current version on bower I noticed that if you specify a callback, it gets stringified and requested of the server:

```
WARN [web-server]: 404: /base/dist/fixtures/function%20()%20%7B%20%20%20%20%20%20%20%20fixtureWin%20=%20fixtures.window();%20%20%20%20%20%20%20%20done();%20%20%20%20%20%20%7D?1418238967460
```

I am pretty sure this is due to this line:

https://github.com/badunk/js-fixtures/blob/master/fixtures.js#L34

Since you don't `pop()` the cb argument, it gets passed in as a callback as well as a template. I'll send a PR. Also, if you could update the version on bower after this, it would be most helpful!

**Comment by anacronw** [comment]
Commented on #26.  Should be a non issue on master, but I've added a new bower version.

Thanks!
