### ISSUE TITLE
Chrome fails to find elements by classname in an iframe, if the classname contains capital letters

### ISSUE THREAD

**Issue by zedd45** [anacronw/js-fixtures#9]
This isn't directly related to js-fixtures, but I thought it might be nice to let other people know that the issue exists:
https://code.google.com/p/chromium/issues/detail?id=174660

I apologize in advance for making this an issue against this project; I think it will be useful for your users to see, so they don't spend hours trying to track down why they can't find elements, or blame your nice library.

**Comment by anacronw** [comment]
that's interesting, I'll take a look at how I can work around that

thanks

**Comment by zedd45** [comment]
Thank you for the awesome port! Hopefully, Chromium will patch this issue quickly.

**Comment by anacronw** [comment]
hm, I learned a couple of things:
1. Case sensitivity in attribute names/values across html/javascript is a very confusing topic:
   http://dev.w3.org/csswg/selectors/#case-sensitive
   https://developer.mozilla.org/en-US/docs/Case_Sensitivity_in_class_and_id_Names
   http://javascript.info/tutorial/attributes-and-custom-properties
2. the id attribute behaves basically the same way (with # selector), its not specific to class attribute
3. case-sensitivity seems to be preserved when you setAttribute('class', 'cRaZyCaSe') after first appending the dom element.  Ie, if you do this, it works:

``` javascript
var div = document.createElement('div')
iframeDoc.appendChild(div)
div.setAttribute('class', 'HelloWorld'); // this switched places with the 2nd line
iframeDoc.querySelector('.HelloWorld'); // this returns the div
```

**Comment by zedd45** [comment]
I see the issue: if you add the classname to the div / node before appending it to the iframe, Chrome seems unable to find it. 

I'm co-authoring a test for a jQuery plugin that does quite a bit of DOM creation / document fragments on the fly, so I'm not sure if we'll be able to remedy our issue in this manner, but I very much appreciate the effort you put into looking into this issue. 

PS:
here's a fiddle confirming your observations:
http://jsfiddle.net/jvS46/3/
